app:
  host: "0.0.0.0"
  port: 80
  root_password: "root"

postgres:
  username: "user"
  password: "user"
  addr: "localhost:5432/hjkl_db?sslmode=disable"

redis:
  addr: "localhost:6379"
  db: 0
  password: ""
