services:
  api:
    container_name: hjkl-api
    build:
      context: .
      dockerfile: air.dockerfile
    ports:
      - "5000:80"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - hjkl-network
    environment:
      - HJKL_POSTGRES_USERNAME=user
      - HJKL_POSTGRES_PASSWORD=user
      - HJKL_POSTGRES_ADDR=hjkl-postgres:5432/hjkl_db?sslmode=disable
      - HJKL_REDIS_ADDR=hjkl-redis:6379
    volumes:
      - ./:/app
    healthcheck:
      test: curl -f http://localhost:80/health || exit 1
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
  redis:
    container_name: hjkl-redis
    image: redis
    restart: always
    ports:
      - "5001:6379"
    networks:
      - hjkl-network
    volumes:
      - cache-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  postgres:
    container_name: hjkl-postgres
    image: postgres
    ports:
      - "5002:5432"
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=hjkl_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hjkl-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d hjkl_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
  adminer:
    container_name: hjkl-adminer
    image: adminer
    restart: always
    ports:
      - 5003:8080
    networks:
      - hjkl-network
  migrate:
    container_name: hjkl-migrate
    image: migrate/migrate
    networks:
      - hjkl-network
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://user:user@hjkl-postgres:5432/hjkl_db?sslmode=disable",
        "up"
      ]
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

networks:
  hjkl-network:
    driver: bridge

volumes:
  postgres-data:
  cache-data:
