basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Just an api.
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: HJKL API
  version: "0.1"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: just returns hello message
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Say hello
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
