basePath: /
definitions:
  types.Message:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Just an api.
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: HJKL API
  version: "0.1"
paths:
  /api/hello:
    get:
      consumes:
      - application/json
      description: just returns hello message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.Message'
      summary: Say hello
  /health:
    get:
      description: Healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.Message'
      summary: Healthcheck
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
